server:
  port: 10010
#logging:
#  level:
#    cn.itcast: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
spring:
  cloud:
    gateway:
      routes:
        - id: GoUserService #规则id
          uri: lb://user-service #负载均衡到user-service服务上
          predicates:
            - Path=/tb-user/** #端口号后边是不是以tb-user开头，是的换就负载均衡到user-service服务上
        - id: GoOrderService
          uri: lb://order-service
          predicates:
            #- Path=/tb-order/** #端口号后边是不是以tb-user开头，是的换就负载均衡到order-service服务上
            - Path=/order-tbl/**
      default-filters:
        - AddRequestHeader=li,xiaoliniubai
        - AddRequestHeader=origin,xiaoliniubai
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.46.130:3306/cloud_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: general
      password: general

#mybatis依赖和数据库配置缺一不可，只要有缺的getway就没办法启动
