server:
  port: 8083
spring:
  application:
    #应用的名称
    name: dubboorder-service
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.46.130:3306/cloud_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: general
      password: general
  redis:
    host: 192.168.46.130  # Redis 服务器地址
    port: 6379       # Redis 服务器端口号
    password: root      # Redis 服务器密码
    timeout: 2000    # 连接超时时间，单位毫秒
    jedis:
      pool:
        # 连接池最大连接数，可选，默认值为8
        max-active: 8
        # 连接池最大空闲连接数，可选，默认值为8
        max-idle: 8
        # 连接池最小空闲连接数，可选，默认值为0
        min-idle: 0
  cache:
    redis:
      time-to-live: 1800000 #缓存的过期时间被设置为1800000毫秒（30分钟）
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#dubbo配置
dubbo:
  application:
    name: dubboorder-service
  registry:
    address: nacos://192.168.46.132:8848  #使用cloud的注册中心
  consumer:
    check: false   #dubbo默认有启动检查
    retries: 0     #dubbo内置的重试机制








