server:
  port: 8089
spring:
  batch:
    job:
      enabled: false   #false表示不随SpringBootApplication启动而自动运行
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springbatch?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 初始化数据库，文件在依赖jar包中
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql
      #mode: always
      mode: never

#这里要注意， sql.init.model 第一次启动为always， 后面启动需要改为never，否则每次执行SQL都会异常。

mybatis:
  configuration:
    default-executor-type: batch    #批量执行更新操作（Insert/Update/Delete），减少与数据库的交互次数。


job:
  data:
    path: C:/Users/28637/Desktop/草稿/存款批处理培训
